"""
Render a verified DB row to a Markdown file for the GitHub Pages site.
Copies the chosen figure into docs/assets/figures/ so it's servable
alongside the rendered page.
"""

import shutil
import sqlite3
from pathlib import Path


def render_paper(paper: sqlite3.Row, docs_dir: str = "docs") -> str:
    """
    Write docs/papers/<arxiv_id>.md from a verified `papers` row.
    Returns the path to the written Markdown file (as a string, for storing
    back into the DB's markdown_path column).
    """
    docs_path = Path(docs_dir)
    papers_dir = docs_path / "papers"
    figures_dir = docs_path / "assets" / "figures"
    papers_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)

    arxiv_id = paper["arxiv_id"]
    clean_id = arxiv_id.split("v")[0] if "v" in arxiv_id else arxiv_id

    figure_markdown = ""
    if paper["figure_path"]:
        src = Path(paper["figure_path"])
        if src.exists():
            dest_name = f"{arxiv_id}{src.suffix}"
            dest = figures_dir / dest_name
            shutil.copy(src, dest)
            figure_markdown = f"![Key figure from {arxiv_id}](../assets/figures/{dest_name})\n\n"

    authors = paper["authors"] or ""
    tags = paper["matched_tags"] or ""

    content = f"""---
title: "{paper['title']}"
arxiv_id: "{arxiv_id}"
published: "{paper['published']}"
---

# {paper['title']}

**Authors:** {authors}
**Published:** {paper['published']}
**Tags:** {tags}
**arXiv:** [{arxiv_id}](https://arxiv.org/abs/{clean_id}) | [PDF](https://arxiv.org/pdf/{clean_id})

{figure_markdown}{paper['draft']}

---

*Generated by {paper['generator_model']}, fact-checked by {paper['verifier_model']}.*
"""

    output_path = papers_dir / f"{arxiv_id}.md"
    output_path.write_text(content)
    return str(output_path)


if __name__ == "__main__":
    # Smoke test using the same row shape db.py's smoke test writes.
    from db import get_connection, upsert_paper

    test_db = "test_render.db"
    Path(test_db).unlink(missing_ok=True)
    conn = get_connection(test_db)

    upsert_paper(conn, {
        "arxiv_id": "2609.17382v1",
        "title": "Assessing ionospheric effects on image quality in the LOFAR Decametre Sky Survey",
        "authors": ["Test Author One", "Test Author Two"],
        "abstract": "Test abstract.",
        "published": "2026-09-14",
        "tag_score": 2,
        "matched_tags": ["facility_lofar", "calibration"],
        "draft": "## Why This Matters\nIonospheric decorrelation affects LOFAR imaging quality in ways that vary night to night.\n\n## Key Results\nDecorrelation time of ~63s measured at 30 MHz.",
        "verified": 1,
        "verify_notes": "Minor rounding discrepancies, otherwise accurate",
        "generator_model": "DeepSeek-V3.2",
        "verifier_model": "Mistral-Large-3-675B-Instruct-2512",
        "figure_path": "arxiv_cache/figures/2609.17382v1_p7_0.png",
        "markdown_path": None,
    })

    row = conn.execute("SELECT * FROM papers WHERE arxiv_id = ?", ("2609.17382v1",)).fetchone()
    md_path = render_paper(row, docs_dir="test_docs")
    print(f"Rendered: {md_path}")
    print(f"Figure copied: {Path('test_docs/assets/figures').glob('*')}")
    print(Path(md_path).read_text())

    conn.close()
    Path(test_db).unlink()
    import shutil as sh
    sh.rmtree("test_docs")
    print("Smoke test passed, test artifacts cleaned up")
